theme: minima
title: Doitforonoreason's homepage
description: Where I occasinally post thoughts

header_pages:
  - index.md
  - projects.md
  - puzzles.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
