theme: minima
title: Doitforonoreason's homepage
description: Where I occasionally post thoughts

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /cool-stuff/:name/

kramdown:
  math_engine: mathjax

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
